CREATE TABLE CARTS
(
    ID           NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    USER_ID      NUMBER                           NOT NULL,
    CREATED_AT   TIMESTAMP(6)                     NOT NULL,
    MODIFIED_AT  TIMESTAMP(6)                     NOT NULL,
    CREATED_BY   NUMBER,
    MODIFIED_BY  NUMBER
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX UK_CARTS_USER_ID ON CARTS
    (USER_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CARTS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE CART_ITEMS
(
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    CART_ID     NUMBER                            NOT NULL,
    PRODUCT_ID  NUMBER                            NOT NULL,
    QUANTITY    NUMBER(10)                        NOT NULL,
    UNIT_PRICE  NUMBER(12,2)                      NOT NULL
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX UK_CART_PRODUCT ON CART_ITEMS
    (CART_ID, PRODUCT_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CART_ITEMS ADD (
  CONSTRAINT CHK_CART_ITEMS_PRICE
  CHECK (UNIT_PRICE > 0)
,  CONSTRAINT CHK_CART_ITEMS_QUANTITY
  CHECK (QUANTITY > 0)
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  CONSTRAINT UK_CART_PRODUCT
  UNIQUE (CART_ID, PRODUCT_ID)
  USING INDEX UK_CART_PRODUCT);


CREATE TABLE CATEGORIES
(
    ID           NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    NAME         VARCHAR2(120 BYTE)               NOT NULL,
    DESCRIPTION  VARCHAR2(500 BYTE),
    CODE         VARCHAR2(50 BYTE)                NOT NULL,
    IS_ACTIVE    NUMBER(1)                        DEFAULT 1                     NOT NULL,
    CREATED_AT   TIMESTAMP(6)                     NOT NULL,
    MODIFIED_AT  TIMESTAMP(6)                     NOT NULL,
    CREATED_BY   NUMBER,
    MODIFIED_BY  NUMBER
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE CATEGORIES ADD (
  CONSTRAINT CHK_CATEGORIES_IS_ACTIVE
  CHECK (IS_ACTIVE IN (0, 1))
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  UNIQUE (CODE)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE INVENTORIES
(
    ID                 NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    PRODUCT_ID         NUMBER                     NOT NULL,
    TOTAL_QUANTITY     NUMBER(10)                 DEFAULT 0                     NOT NULL,
    RESERVED_QUANTITY  NUMBER(10)                 DEFAULT 0                     NOT NULL,
    VERSION            NUMBER                     DEFAULT 0                     NOT NULL,
    CREATED_AT         TIMESTAMP(6)               NOT NULL,
    MODIFIED_AT        TIMESTAMP(6)               NOT NULL,
    CREATED_BY         NUMBER,
    MODIFIED_BY        NUMBER
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE INVENTORIES ADD (
  CONSTRAINT CHK_INVENTORIES_RESERVED_NOT_ABOVE_TOTAL
  CHECK (RESERVED_QUANTITY <= TOTAL_QUANTITY)
,  CONSTRAINT CHK_INVENTORIES_RESERVED_QTY
  CHECK (RESERVED_QUANTITY >= 0)
,  CONSTRAINT CHK_INVENTORIES_TOTAL_QTY
  CHECK (TOTAL_QUANTITY >= 0)
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE IN_ITEM
(
    ITEM_NO     NUMBER(30),
    ITEM_NAME   VARCHAR2(500 BYTE),
    SUBITEM_OF  NUMBER
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE IN_ITEM ADD (
  PRIMARY KEY
  (ITEM_NO)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE ORDERS
(
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    ORDER_NUMBER  RAW(16)                         DEFAULT SYS_GUID ()           NOT NULL,
    USER_ID       NUMBER                          NOT NULL,
    STATUS        VARCHAR2(30 BYTE)               NOT NULL,
    TOTAL_AMOUNT  NUMBER(12,2)                    NOT NULL,
    CANCELLED_AT  TIMESTAMP(6),
    CREATED_AT    TIMESTAMP(6)                    NOT NULL,
    MODIFIED_AT   TIMESTAMP(6)                    NOT NULL,
    CREATED_BY    NUMBER,
    MODIFIED_BY   NUMBER
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE ORDERS ADD (
  CONSTRAINT CHK_ORDERS_CANCELLED_RULE
  CHECK (   (STATUS = 'CANCELLED' AND CANCELLED_AT IS NOT NULL)
            OR (STATUS <> 'CANCELLED' AND CANCELLED_AT IS NULL))
,  CONSTRAINT CHK_ORDERS_STATUS
  CHECK (STATUS IN ('CREATED',
                    'CONFIRMED',
                    'PAID',
                    'CANCELLED'))
,  CONSTRAINT CHK_ORDERS_TOTAL_AMOUNT
  CHECK (TOTAL_AMOUNT >= 0)
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE ORDER_ITEMS
(
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    ORDER_ID      NUMBER                          NOT NULL,
    PRODUCT_ID    NUMBER                          NOT NULL,
    PRODUCT_NAME  VARCHAR2(200 BYTE)              NOT NULL,
    UNIT_PRICE    NUMBER(12,2)                    NOT NULL,
    QUANTITY      NUMBER(10)                      NOT NULL,
    TOTAL_PRICE   NUMBER(12,2)                    NOT NULL
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE ORDER_ITEMS ADD (
  CONSTRAINT CHK_ORDER_ITEMS_QUANTITY
  CHECK (QUANTITY > 0)
,  CONSTRAINT CHK_ORDER_ITEMS_TOTAL_PRICE
  CHECK (TOTAL_PRICE > 0)
,  CONSTRAINT CHK_ORDER_ITEMS_UNIT_PRICE
  CHECK (UNIT_PRICE > 0)
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE PAYMENT_HISTORY
(
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    ORDER_ID      NUMBER                          NOT NULL,
    SESSION_ID    VARCHAR2(255 BYTE)              NOT NULL,
    PAYMENT_LINK  VARCHAR2(2048 BYTE)             NOT NULL,
    STATUS        VARCHAR2(30 BYTE)               NOT NULL,
    EXPIRES_AT    TIMESTAMP(6)                    NOT NULL,
    CREATED_AT    TIMESTAMP(6)                    NOT NULL,
    MODIFIED_AT   TIMESTAMP(6)                    NOT NULL,
    CREATED_BY    NUMBER,
    MODIFIED_BY   NUMBER
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE PAYMENT_HISTORY ADD (
  CONSTRAINT CHK_PAYMENT_HISTORY_STATUS
  CHECK (STATUS IN ('INITIATED',
                    'SUCCESS',
                    'FAILED',
                    'CANCELLED'))
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  UNIQUE (SESSION_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE PERMISSIONS
(
    CREATED_AT   TIMESTAMP(9)                     NOT NULL,
    CREATED_BY   NUMBER(19),
    ID           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    MODIFIED_AT  TIMESTAMP(9)                     NOT NULL,
    MODIFIED_BY  NUMBER(19),
    CODE         VARCHAR2(100 CHAR)               NOT NULL,
    NAME         VARCHAR2(120 CHAR)               NOT NULL,
    DESCRIPTION  VARCHAR2(500 CHAR)
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE PERMISSIONS ADD (
  CHECK ((code in ('PERMISSION_PRODUCT_READ','PERMISSION_PRODUCT_CREATE','PERMISSION_PRODUCT_UPDATE','PERMISSION_PRODUCT_DELETE','PERMISSION_CATEGORY_READ','PERMISSION_CATEGORY_CREATE','PERMISSION_CATEGORY_UPDATE','PERMISSION_CATEGORY_DELETE','PERMISSION_INVENTORY_READ','PERMISSION_INVENTORY_MANAGE','PERMISSION_ORDER_READ','PERMISSION_ORDER_UPDATE','PERMISSION_ORDER_CANCEL','PERMISSION_USER_READ','PERMISSION_USER_MANAGE','PERMISSION_ROLE_READ','PERMISSION_ROLE_CREATE','PERMISSION_ROLE_UPDATE','PERMISSION_ROLE_DELETE','PERMISSION_ROLE_ASSIGN','PERMISSION_READ','PERMISSION_CREATE','PERMISSION_UPDATE','PERMISSION_DELETE','PERMISSION_ASSIGN')))
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  UNIQUE (CODE)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE PRODUCTS
(
    ID             NUMBER(19)                     NOT NULL,
    CREATED_AT     TIMESTAMP(9) WITH TIME ZONE    NOT NULL,
    CURRENT_STOCK  NUMBER(10)                     NOT NULL,
    DESCRIPTION    VARCHAR2(500 CHAR),
    NAME           VARCHAR2(160 CHAR)             NOT NULL,
    SKU            VARCHAR2(80 CHAR)              NOT NULL,
    UPDATED_AT     TIMESTAMP(9) WITH TIME ZONE    NOT NULL,
    VERSION        NUMBER(19)                     NOT NULL
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX UKFHMD06DSMJ6K0N90SWSH8IE9G ON PRODUCTS
    (SKU)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PRODUCTS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  CONSTRAINT UKFHMD06DSMJ6K0N90SWSH8IE9G
  UNIQUE (SKU)
  USING INDEX UKFHMD06DSMJ6K0N90SWSH8IE9G);


CREATE TABLE ROLES
(
    CREATED_AT   TIMESTAMP(9)                     NOT NULL,
    CREATED_BY   NUMBER(19),
    ID           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    MODIFIED_AT  TIMESTAMP(9)                     NOT NULL,
    MODIFIED_BY  NUMBER(19),
    CODE         VARCHAR2(80 CHAR)                NOT NULL,
    NAME         VARCHAR2(120 CHAR)               NOT NULL,
    DESCRIPTION  VARCHAR2(500 CHAR)
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE ROLES ADD (
  CHECK ((code in ('ADMIN','CUSTOMER','PRODUCT_MANAGER','INVENTORY_MANAGER','SUPPORT_AGENT')))
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  UNIQUE (CODE)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE ROLE_PERMISSIONS
(
    PERMISSION_ID  NUMBER(19)                     NOT NULL,
    ROLE_ID        NUMBER(19)                     NOT NULL
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE ROLE_PERMISSIONS ADD (
  PRIMARY KEY
  (PERMISSION_ID, ROLE_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE STOCK_MOVEMENTS
(
    ID           NUMBER(19)                       NOT NULL,
    CREATED_AT   TIMESTAMP(9) WITH TIME ZONE      NOT NULL,
    QUANTITY     NUMBER(10)                       NOT NULL,
    REMARKS      VARCHAR2(500 CHAR),
    STOCK_AFTER  NUMBER(10)                       NOT NULL,
    TYPE         VARCHAR2(20 CHAR)                NOT NULL,
    PRODUCT_ID   NUMBER(19)                       NOT NULL
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE STOCK_MOVEMENTS ADD (
  CHECK ((type in ('STOCK_IN','STOCK_OUT')))
,  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE USERS
(
    USER_NO       NUMBER(19),
    FIRST_NAME    VARCHAR2(100 CHAR)              NOT NULL,
    LAST_NAME     VARCHAR2(100 CHAR),
    USERNAME      VARCHAR2(100 CHAR)              NOT NULL,
    PHONE_NUMBER  VARCHAR2(30 CHAR),
    PASSWORD      VARCHAR2(255 CHAR)              NOT NULL,
    EMAIL         VARCHAR2(150 CHAR)              NOT NULL,
    IS_ACTIVE     NUMBER(1)                       DEFAULT 1                     NOT NULL,
    CREATED_AT    TIMESTAMP(9),
    CREATED_BY    NUMBER(19),
    MODIFIED_AT   TIMESTAMP(9),
    MODIFIED_BY   NUMBER(19)
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
ENABLE ROW MOVEMENT;


ALTER TABLE USERS ADD (
  CHECK ((IS_ACTIVE IN (0, 1)))
,  PRIMARY KEY
  (USER_NO)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  UNIQUE (USERNAME)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  UNIQUE (EMAIL)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE USER_ROLES
(
    ROLE_ID  NUMBER(19)                           NOT NULL,
    USER_ID  NUMBER(19)                           NOT NULL
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE USER_ROLES ADD (
  PRIMARY KEY
  (ROLE_ID, USER_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


CREATE TABLE "flyway_schema_history"
(
    "installed_rank"  INTEGER                     NOT NULL,
    "version"         VARCHAR2(50 BYTE),
    "description"     VARCHAR2(200 BYTE)          NOT NULL,
    "type"            VARCHAR2(20 BYTE)           NOT NULL,
    "script"          VARCHAR2(1000 BYTE)         NOT NULL,
    "checksum"        INTEGER,
    "installed_by"    VARCHAR2(100 BYTE)          NOT NULL,
    "installed_on"    TIMESTAMP(6)                DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    "execution_time"  INTEGER                     NOT NULL,
    "success"         NUMBER(1)                   NOT NULL
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX "flyway_schema_history_pk" ON "flyway_schema_history"
    ("installed_rank")
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE "flyway_schema_history" ADD (
  CONSTRAINT "flyway_schema_history_pk"
  PRIMARY KEY
  ("installed_rank")
  USING INDEX "flyway_schema_history_pk");


-- Sequence ISEQ$$_72923 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_72932 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_72936 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_72940 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_72946 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_72952 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_72957 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_73008 is created automatically by Oracle for use with an Identity column


-- Sequence ISEQ$$_73018 is created automatically by Oracle for use with an Identity column


CREATE INDEX IDX_CART_ITEMS_CART_ID ON CART_ITEMS
    (CART_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_CART_ITEMS_PRODUCT_ID ON CART_ITEMS
    (PRODUCT_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_INVENTORIES_PRODUCT_ID ON INVENTORIES
    (PRODUCT_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_ORDERS_ORDER_NUMBER ON ORDERS
    (ORDER_NUMBER)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_ORDERS_STATUS ON ORDERS
    (STATUS)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_ORDERS_USER_ID ON ORDERS
    (USER_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_ORDER_ITEMS_ORDER_ID ON ORDER_ITEMS
    (ORDER_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_ORDER_ITEMS_PRODUCT_ID ON ORDER_ITEMS
    (PRODUCT_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_PAYMENT_HISTORY_ORDER_ID ON PAYMENT_HISTORY
    (ORDER_ID)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_PAYMENT_HISTORY_ORDER_STATUS ON PAYMENT_HISTORY
    (ORDER_ID, STATUS)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_PAYMENT_HISTORY_STATUS ON PAYMENT_HISTORY
    (STATUS)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX IDX_PAYMENT_HISTORY_STATUS_EXPIRES_AT ON PAYMENT_HISTORY
    (STATUS, EXPIRES_AT)
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--  There is no statement for index LMS.SYS_C007480.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007481.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007504.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007510.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007518.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007532.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007543.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007554.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007555.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007610.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007611.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007624.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007631.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007632.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007635.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007739.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007747.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007862.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007863.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007864.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007886.
--  The object is created when the parent object is created.

CREATE INDEX "flyway_schema_history_s_idx" ON "flyway_schema_history"
    ("success")
    LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE TABLE REFRESH_TOKENS
(
    REFRESH_TOKENS_NO  NUMBER(19),
    USER_NO            NUMBER(19)                 NOT NULL,
    TOKEN_HASH         VARCHAR2(64 BYTE)          NOT NULL,
    REVOKED            NUMBER(1)                  DEFAULT 0                     NOT NULL,
    CREATED_AT         TIMESTAMP(9)               NOT NULL,
    CREATED_BY         NUMBER(19),
    EXPIRES_AT         TIMESTAMP(9)               NOT NULL,
    MODIFIED_AT        TIMESTAMP(9),
    MODIFIED_BY        NUMBER(19)
)
    TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
ENABLE ROW MOVEMENT;


ALTER TABLE REFRESH_TOKENS ADD (
  CHECK ((REVOKED IN (0, 1)))
,  PRIMARY KEY
  (REFRESH_TOKENS_NO)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
,  UNIQUE (TOKEN_HASH)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               ));


--  There is no statement for index LMS.SYS_C007871.
--  The object is created when the parent object is created.

--  There is no statement for index LMS.SYS_C007872.
--  The object is created when the parent object is created.

ALTER TABLE CART_ITEMS ADD (
  CONSTRAINT FK_CART_ITEMS_CART
  FOREIGN KEY (CART_ID)
  REFERENCES CARTS (ID));

ALTER TABLE ORDER_ITEMS ADD (
  CONSTRAINT FK_ORDER_ITEMS_ORDER
  FOREIGN KEY (ORDER_ID)
  REFERENCES ORDERS (ID));

ALTER TABLE PAYMENT_HISTORY ADD (
  CONSTRAINT FK_PAYMENT_HISTORY_ORDER
  FOREIGN KEY (ORDER_ID)
  REFERENCES ORDERS (ID));

ALTER TABLE ROLE_PERMISSIONS ADD (
  CONSTRAINT FKEGDK29EIY7MDTEFY5C7EIRR6E
  FOREIGN KEY (PERMISSION_ID)
  REFERENCES PERMISSIONS (ID)
,  CONSTRAINT FKN5FOTDGK8D1XVO8NAV9UV3MUC
  FOREIGN KEY (ROLE_ID)
  REFERENCES ROLES (ID));

ALTER TABLE STOCK_MOVEMENTS ADD (
  CONSTRAINT FKJCAAG8OGFJXPWMQYPI1WFDAOG
  FOREIGN KEY (PRODUCT_ID)
  REFERENCES PRODUCTS (ID));

ALTER TABLE USER_ROLES ADD (
  CONSTRAINT FKH8CIRAMU9CC9Q3QCQIV4UE8A6
  FOREIGN KEY (ROLE_ID)
  REFERENCES ROLES (ID));

ALTER TABLE REFRESH_TOKENS ADD (
  FOREIGN KEY (USER_NO)
  REFERENCES USERS (USER_NO));
