CREATE TABLE USERS
(
    USER_NO         NUMBER (19) PRIMARY KEY,
    FIRST_NAME      VARCHAR2 (100 CHAR) NOT NULL,
    LAST_NAME       VARCHAR2 (100 CHAR),
    USERNAME        VARCHAR2 (100 CHAR) NOT NULL UNIQUE,
    PHONE_NUMBER    VARCHAR2 (30 CHAR),
    PASSWORD        VARCHAR2 (255 CHAR) NOT NULL,
    EMAIL           VARCHAR2 (150 CHAR) NOT NULL UNIQUE,
    IS_ACTIVE       NUMBER (1) DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP (9),
    CREATED_BY      NUMBER (19),
    MODIFIED_AT     TIMESTAMP (9),
    MODIFIED_BY     NUMBER (19)
)
TABLESPACE USERS
LOGGING
NOCOMPRESS
NOCACHE
ENABLE ROW MOVEMENT;