CREATE TABLE REFRESH_TOKENS
(
    REFRESH_TOKENS_NO    NUMBER (19) PRIMARY KEY,
    USER_NO              NUMBER (19) NOT NULL REFERENCES USERS (USER_NO),
    TOKEN_HASH           VARCHAR2 (64 BYTE) NOT NULL UNIQUE,
    REVOKED              NUMBER (1)
                            DEFAULT 0
                            NOT NULL
                            CHECK ((REVOKED IN (0, 1))) ENABLE VALIDATE,
    CREATED_AT           TIMESTAMP (9) NOT NULL,
    CREATED_BY           NUMBER (19),
    EXPIRES_AT           TIMESTAMP (9) NOT NULL,
    MODIFIED_AT          TIMESTAMP (9),
    MODIFIED_BY          NUMBER (19)
)
    TABLESPACE USERS
LOGGING
NOCOMPRESS
NOCACHE
ENABLE ROW MOVEMENT;